[package]
name = "mdlr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
pulldown-cmark = "0.9.2"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
